version: "3.6"

services:
  apiquery:
    build: "."
    command: "api-query-service"
    depends_on:
      - "postgres"
      - "nats"
    ports:
      - "18080:8080"
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "task"
      POSTGRES_USER: "task"
      POSTGRES_PASSWORD: "123456"
      NATS_ADDRESS: "nats:4222"

  command:
    build: "."
    command: "command-service"
    depends_on:
      - "postgres"
      - "nats"
    ports:
      - "28080:8080"
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "task"
      POSTGRES_USER: "task"
      POSTGRES_PASSWORD: "123456"
      NATS_ADDRESS: "nats:4222"

  postgres:
    build: "./postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "task"
      POSTGRES_USER: "task"
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
  
  nats:
    image: "nats-streaming"
    restart: "always"
    ports:
      - "4222:4222"
